### ISSUE TITLE
缺少npm包~taro-parse/dist/style/main.scss，

### ISSUE THREAD

**Issue by xiebanglong** [werfei/taro-parse#10]
![image](https://user-images.githubusercontent.com/44019629/84480278-e002bf80-acc6-11ea-8a95-4cc041615091.png)

**Comment by werfei** [comment]
你看下node_modules这个目录下面的文件是正常的吗
![图片](https://user-images.githubusercontent.com/18606985/84591672-ec2b8000-ae72-11ea-90ef-c3dcc1811712.png)

taro-parse/dist/style 下面有样式文件么

**Comment by werfei** [comment]
暂时关闭了
