### ISSUE TITLE
图片展示不了

### ISSUE THREAD

**Issue by MOOO-M** [werfei/taro-parse#11]
<figure class="image">![]( http://biq.zdvictory.com:7003/EGB-ADMIN-BOOT/api/attachment/download/YmlxdGVzdCQkSU5GT19DTVMvYTE1NTU2YTMtMTUxOS00OWI0LWEzMDktZTZiMmM2MGZhODAzLmpwZw==?serviceName=MinioAttachService)</figure>

**Comment by werfei** [comment]
如果是小程序里面，得配置域名
