### ISSUE TITLE
图片不能控制mode，可不可以加一个mode属性

### ISSUE THREAD

**Issue by Alubb77** [werfei/taro-parse#2]
https://developers.weixin.qq.com/miniprogram/dev/component/image.html

scaleToFill | 缩放模式，不保持纵横比缩放图片，使图片的宽高完全拉伸至填满 image 元素 |  
aspectFit | 缩放模式，保持纵横比缩放图片，使图片的长边能完全显示出来。也就是说，可以完整地将图片显示出来。 |  
aspectFill | 缩放模式，保持纵横比缩放图片，只保证图片的短边能完全显示出来。也就是说，图片通常只在水平或垂直方向是完整的，另一个方向将会发生截取。 |  
widthFix | 缩放模式，宽度不变，高度自动变化，保持原图宽高比不变 |  
heightFix | 缩放模式，高度不变，宽度自动变化，保持原图宽高比不变 | 2.10.3
top | 裁剪模式，不缩放图片，只显示图片的顶部区域 |  
bottom | 裁剪模式，不缩放图片，只显示图片的底部区域 |  
center | 裁剪模式，不缩放图片，只显示图片的中间区域 |  
left | 裁剪模式，不缩放图片，只显示图片的左边区域 |  
right | 裁剪模式，不缩放图片，只显示图片的右边区域 |  
top left | 裁剪模式，不缩放图片，只显示图片的左上边区域 |  
top right | 裁剪模式，不缩放图片，只显示图片的右上边区域 |  
bottom left | 裁剪模式，不缩放图片，只显示图片的左下边区域 |  
bottom right | 裁剪模式，不缩放图片，只显示图片的右下边区域

**Comment by werfei** [comment]
markdown里面有这种设置么？你是要全局配置还是每个图片文件单独配置？如果单独配置，markdown语法是什么呢，还是说用html方式插入图片？

**Comment by luyukunluyukun** [comment]
> markdown里面有这种设置么？你是要全局配置还是每个图片文件单独配置？如果单独配置，markdown语法是什么呢，还是说用html方式插入图片？

他可能是说解析image的时候添加mode属性，用来控制图片

**Comment by werfei** [comment]
@luyukunluyukun 我知道他那意思，但是这个是解析markdown文档的，markdown文档中如何设定图片的mode属性呢？解析得知道规则才能加，如果是全局加这个属性倒是好处理，单个文件的肯定要从单个图片解析时获取mode属性

**Comment by pearmini** [comment]
应该增加一个全局的属性 mode 去控制图片的 mode。因为 image mode 的默认值是 scallToFill，会对所有图片进行伸缩，这样会导致所有图片在设置同一个 width 和 height 的情况下变形。

**Comment by werfei** [comment]
> 
> 
> 应该增加一个全局的属性 mode 去控制图片的 mode。因为 image mode 的默认值是 scallToFill，会对所有图片进行伸缩，这样会导致所有图片在设置同一个 width 和 height 的情况下变形。

这个项目暂时不动了，后面有时间做基于3.0的了，这个解析引擎毕竟不是开源的，全局加这种方式倒还好处理点，一会儿我给加上吧
