### ISSUE TITLE
图片预览怎么能左右滑动看到全部的

### ISSUE THREAD

**Issue by hzfvictory** [werfei/taro-parse#5]

**Comment by werfei** [comment]
这个暂时没有，考虑后面可以加进去

**Comment by werfei** [comment]
已实现，请更新到1.1.3版本

**Comment by hzfvictory** [comment]
牛逼，一会试试




| |
和振峰
|
|
邮箱：feng960106@163.com
|

签名由 网易邮箱大师 定制

在2020年04月17日 21:18，werfei 写道：

已实现，请更新到1.1.3版本
