### ISSUE TITLE
关于eslint警告key不能直接使用index的问题

### ISSUE THREAD

**Issue by programmermark** [werfei/taro-parse#6]
源代码运行时，会提示很多的警告，不应该使用index直接作为key。建议修改这些文件，用Date.now()+Math.random替换key，就可以避免这个问题。
还有，建议作者可以优化下markdown中<code></code>代码块包括的区域的样式。

**Comment by werfei** [comment]
eslint警告问题，在渲染前给定数据索引值
markdown样式light主题下切换成vs主题，这个每个人的审美不一样，可以自行覆盖样式
新的改动已添加到1.1.4版本中
