### ISSUE TITLE
[Feature Request] 是否可以增加一个 parse 完成的事件

### ISSUE THREAD

**Issue by polichan** [werfei/taro-parse#8]
因为有的时候，`content` 数据量比较大，如果能有一个 `parse`  完成后的事件，就可以用 `loading` 在`parse`  完成之前占位，转换完就移除。

**Comment by werfei** [comment]
好的，这两天我看下

**Comment by werfei** [comment]
版本1.1.5已添加，后期这个组件计划自己重新写一遍解析部分
